### ISSUE TITLE
word2vec. loading model.bin

### ISSUE THREAD

**Issue by cloud9-xx** [liuhuigmail/DeepSmellDetection#3]
When I try to run the model locally. I get an error regarding new_model.bin.trainables.syn1neg.npy that it failed to interpret it as a pickle. Below is the contect of npy file.

version https://git-lfs.github.com/spec/v1oid sha256:bf1ccc06a3c5264d10b1d3e0a8f6423a966b5ba9952d0d224ae9030be70094d2
size 485452928

**Comment by liuhuigmail** [comment]
@cloud9-xx  Would you please attach the screen shot to reveal the details of the error message.

**Comment by cloud9-xx** [comment]
This is the error I get. I don't know what I am doing wrong. 

![image](https://user-images.githubusercontent.com/2872215/121755252-01cf9600-cb17-11eb-98c7-2d2e1bd39e01.png)

**Comment by TyrantJin** [comment]
This problem is mainly caused by the storage space limitation of  a repo. This file is deleted.We recommend that you retrain the model. The corpus comes from all the name(**method name** and **class name**) in [https://github.com/liuhuigmail/DeepSmellDetection/tree/master/feature%20envy/Data/Database](url).

**Comment by TyrantJin** [comment]
@cloud9-xx You can also download the model from [https://zenodo.org/record/4965680#.YMn-hDC-uUk](url)

**Comment by cloud9-xx** [comment]
Good Afternoon,

Thank you very much.

kind regards,

Mustafa el Bouazzaoui

**Comment by liuhuigmail** [comment]
problem solved
